import { useState, useMemo } from 'react'
import { Bot, Copy, Check, Download, Sparkles, ChevronDown, ChevronUp, FileText, Terminal, Zap } from 'lucide-react'

interface Skill {
  name: string
  description: string
  enabled: boolean
}

const DEFAULT_SKILLS: Skill[] = [
  { name: 'web_search', description: 'Search the web for real-time information', enabled: true },
  { name: 'web_extract', description: 'Extract content from web pages', enabled: true },
  { name: 'terminal', description: 'Execute shell commands', enabled: false },
  { name: 'file_read', description: 'Read files from the filesystem', enabled: false },
  { name: 'file_write', description: 'Write files to the filesystem', enabled: false },
  { name: 'browser', description: 'Automate browser interactions', enabled: false },
  { name: 'image_gen', description: 'Generate images from text prompts', enabled: false },
  { name: 'tts', description: 'Convert text to speech', enabled: false },
  { name: 'coding', description: 'Write and execute code', enabled: false },
  { name: 'vision', description: 'Analyze images and screenshots', enabled: false },
]

export default function AgentBuilder() {
  const [name, setName] = useState('')
  const [description, setDescription] = useState('')
  const [provider, setProvider] = useState('openai')
  const [model, setModel] = useState('gpt-4o')
  const [systemPrompt, setSystemPrompt] = useState('')
  const [instructions, setInstructions] = useState('')
  const [temperature, setTemperature] = useState(0.7)
  const [maxTokens, setMaxTokens] = useState(2048)
  const [skills, setSkills] = useState<Skill[]>(DEFAULT_SKILLS)
  const [copied, setCopied] = useState<string | null>(null)
  const [showPreview, setShowPreview] = useState(false)
  const [activeTab, setActiveTab] = useState<'command' | 'skills'>('command')

  const modelsByProvider: Record<string, string[]> = {
    openai: ['gpt-4o', 'gpt-4-turbo', 'gpt-4', 'gpt-3.5-turbo', 'o1', 'o1-mini'],
    anthropic: ['claude-3-5-sonnet-20241022', 'claude-3-opus-20240229', 'claude-3-haiku-20240307', 'claude-3.5-sonnet'],
    openrouter: ['openai/gpt-4o', 'anthropic/claude-3.5-sonnet', 'google/gemini-pro', 'meta-llama/llama-3.1-70b'],
  }

  const enabledSkills = useMemo(() => skills.filter(s => s.enabled), [skills])

  const generatedCommand = useMemo(() => {
    const parts: string[] = []
    parts.push(`Agent: ${name || 'My Agent'}`)
    parts.push(`Provider: ${provider}`)
    parts.push(`Model: ${model}`)
    if (description) parts.push(`Description: ${description}`)
    parts.push(`Temperature: ${temperature}`)
    parts.push(`Max Tokens: ${maxTokens}`)
    if (systemPrompt) parts.push(`\nSystem Prompt:\n${systemPrompt}`)
    if (instructions) parts.push(`\nInstructions:\n${instructions}`)
    if (enabledSkills.length > 0) {
      parts.push(`\nSkills: ${enabledSkills.map(s => s.name).join(', ')}`)
    }
    return parts.join('\n')
  }, [name, provider, model, description, temperature, maxTokens, systemPrompt, instructions, enabledSkills])

  const generatedSkillsMd = useMemo(() => {
    let md = `# Skills.md - ${name || 'My Agent'}\n\n`
    md += `> Auto-generated by Moltbook Agent Builder\n\n`
    md += `## Agent Configuration\n\n`
    md += `- **Provider:** ${provider}\n`
    md += `- **Model:** ${model}\n`
    md += `- **Temperature:** ${temperature}\n`
    md += `- **Max Tokens:** ${maxTokens}\n\n`
    if (systemPrompt) {
      md += `## System Prompt\n\n\`\`\`\n${systemPrompt}\n\`\`\`\n\n`
    }
    if (instructions) {
      md += `## Instructions\n\n\`\`\`\n${instructions}\n\`\`\`\n\n`
    }
    if (enabledSkills.length > 0) {
      md += `## Enabled Skills\n\n`
      md += `| Skill | Description |\n|-------|-------------|\n`
      enabledSkills.forEach(s => {
        md += `| ${s.name} | ${s.description} |\n`
      })
      md += `\n`
    }
    md += `## Usage\n\n`
    md += `Copy the command below and paste it into your agent:\n\n`
    md += `\`\`\`\n${generatedCommand}\n\`\`\`\n`
    return md
  }, [name, provider, model, temperature, maxTokens, systemPrompt, instructions, enabledSkills, generatedCommand])

  const fullExport = useMemo(() => {
    return `${generatedCommand}\n\n---\n\n${generatedSkillsMd}`
  }, [generatedCommand, generatedSkillsMd])

  const copyToClipboard = async (text: string, label: string) => {
    try {
      await navigator.clipboard.writeText(text)
      setCopied(label)
      setTimeout(() => setCopied(null), 2000)
    } catch {
      // Fallback
      const ta = document.createElement('textarea')
      ta.value = text
      document.body.appendChild(ta)
      ta.select()
      document.execCommand('copy')
      document.body.removeChild(ta)
      setCopied(label)
      setTimeout(() => setCopied(null), 2000)
    }
  }

  const downloadSkillsMd = () => {
    const blob = new Blob([generatedSkillsMd], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${(name || 'agent').toLowerCase().replace(/\s+/g, '-')}-skills.md`
    a.click()
    URL.revokeObjectURL(url)
  }

  const toggleSkill = (index: number) => {
    setSkills(prev => prev.map((s, i) => i === index ? { ...s, enabled: !s.enabled } : s))
  }

  return (
    <div className="max-w-6xl mx-auto">
      {/* Header */}
      <div className="mb-8">
        <div className="flex items-center gap-3 mb-2">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-violet-500 to-fuchsia-500 flex items-center justify-center">
            <Sparkles className="w-5 h-5 text-white" />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-white">Agent Builder</h1>
            <p className="text-gray-400 text-sm">Create, configure, and export your AI agent with skills</p>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* LEFT: Configuration */}
        <div className="space-y-5">
          {/* Basic Info */}
          <div className="card">
            <h2 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
              <Bot className="w-5 h-5 text-violet-400" />
              Agent Details
            </h2>
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-1.5">Agent Name</label>
                <input
                  type="text"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  className="input"
                  placeholder="e.g., Research Assistant, Code Helper..."
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-1.5">Description</label>
                <input
                  type="text"
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  className="input"
                  placeholder="What does this agent do?"
                />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-300 mb-1.5">Provider</label>
                  <select
                    value={provider}
                    onChange={(e) => {
                      const p = e.target.value
                      setProvider(p)
                      setModel(modelsByProvider[p]?.[0] || '')
                    }}
                    className="input"
                  >
                    <option value="openai">OpenAI</option>
                    <option value="anthropic">Anthropic</option>
                    <option value="openrouter">OpenRouter</option>
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-300 mb-1.5">Model</label>
                  <select
                    value={model}
                    onChange={(e) => setModel(e.target.value)}
                    className="input"
                  >
                    {(modelsByProvider[provider] || []).map((m) => (
                      <option key={m} value={m}>{m}</option>
                    ))}
                  </select>
                </div>
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-300 mb-1.5">
                    Temperature: {temperature}
                  </label>
                  <input
                    type="range"
                    min="0"
                    max="2"
                    step="0.1"
                    value={temperature}
                    onChange={(e) => setTemperature(parseFloat(e.target.value))}
                    className="w-full accent-violet-500"
                  />
                  <div className="flex justify-between text-xs text-gray-500 mt-1">
                    <span>Precise</span>
                    <span>Creative</span>
                  </div>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-300 mb-1.5">Max Tokens</label>
                  <select
                    value={maxTokens}
                    onChange={(e) => setMaxTokens(parseInt(e.target.value))}
                    className="input"
                  >
                    <option value={512}>512</option>
                    <option value={1024}>1,024</option>
                    <option value={2048}>2,048</option>
                    <option value={4096}>4,096</option>
                    <option value={8192}>8,192</option>
                    <option value={16384}>16,384</option>
                  </select>
                </div>
              </div>
            </div>
          </div>

          {/* System Prompt */}
          <div className="card">
            <h2 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
              <Terminal className="w-5 h-5 text-emerald-400" />
              System Prompt
            </h2>
            <textarea
              value={systemPrompt}
              onChange={(e) => setSystemPrompt(e.target.value)}
              className="input min-h-[120px] font-mono text-sm"
              placeholder="You are a helpful assistant that..."
            />
          </div>

          {/* Instructions */}
          <div className="card">
            <h2 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
              <Zap className="w-5 h-5 text-amber-400" />
              Instructions / Commands
            </h2>
            <textarea
              value={instructions}
              onChange={(e) => setInstructions(e.target.value)}
              className="input min-h-[120px] font-mono text-sm"
              placeholder="Step 1: Analyze the user's request...&#10;Step 2: Search for relevant information...&#10;Step 3: Provide a detailed response..."
            />
            <p className="text-xs text-gray-500 mt-2">
              Write step-by-step instructions for your agent. This will be included in the exported command.
            </p>
          </div>

          {/* Skills */}
          <div className="card">
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-lg font-semibold text-white flex items-center gap-2">
                <FileText className="w-5 h-5 text-blue-400" />
                Skills ({enabledSkills.length} enabled)
              </h2>
              <button
                onClick={() => setSkills(prev => prev.map(s => ({ ...s, enabled: !s.enabled })))}
                className="text-xs text-violet-400 hover:text-violet-300 transition-colors"
              >
                {enabledSkills.length === skills.length ? 'Disable All' : 'Enable All'}
              </button>
            </div>
            <div className="grid grid-cols-1 gap-2">
              {skills.map((skill, index) => (
                <button
                  key={skill.name}
                  onClick={() => toggleSkill(index)}
                  className={`flex items-center gap-3 p-3 rounded-lg border transition-all text-left ${
                    skill.enabled
                      ? 'border-violet-500/50 bg-violet-500/10'
                      : 'border-gray-700 bg-gray-800/50 hover:border-gray-600'
                  }`}
                >
                  <div className={`w-4 h-4 rounded border-2 flex items-center justify-center flex-shrink-0 ${
                    skill.enabled ? 'border-violet-500 bg-violet-500' : 'border-gray-600'
                  }`}>
                    {skill.enabled && <Check className="w-3 h-3 text-white" />}
                  </div>
                  <div className="min-w-0">
                    <div className={`text-sm font-medium ${skill.enabled ? 'text-white' : 'text-gray-400'}`}>
                      {skill.name}
                    </div>
                    <div className="text-xs text-gray-500 truncate">{skill.description}</div>
                  </div>
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* RIGHT: Preview & Export */}
        <div className="space-y-5">
          {/* Tab Switcher */}
          <div className="card">
            <div className="flex gap-2 mb-4">
              <button
                onClick={() => setActiveTab('command')}
                className={`flex-1 py-2 px-4 rounded-lg text-sm font-medium transition-all ${
                  activeTab === 'command'
                    ? 'bg-violet-500/20 text-violet-300 border border-violet-500/50'
                    : 'text-gray-400 hover:text-gray-300 border border-transparent'
                }`}
              >
                <div className="flex items-center justify-center gap-2">
                  <Terminal className="w-4 h-4" />
                  Command
                </div>
              </button>
              <button
                onClick={() => setActiveTab('skills')}
                className={`flex-1 py-2 px-4 rounded-lg text-sm font-medium transition-all ${
                  activeTab === 'skills'
                    ? 'bg-violet-500/20 text-violet-300 border border-violet-500/50'
                    : 'text-gray-400 hover:text-gray-300 border border-transparent'
                }`}
              >
                <div className="flex items-center justify-center gap-2">
                  <FileText className="w-4 h-4" />
                  Skills.md
                </div>
              </button>
            </div>

            {/* Command Tab */}
            {activeTab === 'command' && (
              <div>
                <div className="flex items-center justify-between mb-3">
                  <span className="text-sm text-gray-400">Copy this command and paste it to your agent</span>
                  <button
                    onClick={() => copyToClipboard(generatedCommand, 'command')}
                    className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-violet-500/20 text-violet-300 hover:bg-violet-500/30 transition-all text-sm"
                  >
                    {copied === 'command' ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                    {copied === 'command' ? 'Copied!' : 'Copy'}
                  </button>
                </div>
                <pre className="bg-gray-900 border border-gray-700 rounded-lg p-4 text-sm text-gray-300 font-mono whitespace-pre-wrap overflow-auto max-h-[500px]">
                  {generatedCommand}
                </pre>
              </div>
            )}

            {/* Skills.md Tab */}
            {activeTab === 'skills' && (
              <div>
                <div className="flex items-center justify-between mb-3">
                  <span className="text-sm text-gray-400">Download or copy the skills.md file</span>
                  <div className="flex gap-2">
                    <button
                      onClick={downloadSkillsMd}
                      className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-emerald-500/20 text-emerald-300 hover:bg-emerald-500/30 transition-all text-sm"
                    >
                      <Download className="w-3.5 h-3.5" />
                      Download
                    </button>
                    <button
                      onClick={() => copyToClipboard(generatedSkillsMd, 'skills')}
                      className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-violet-500/20 text-violet-300 hover:bg-violet-500/30 transition-all text-sm"
                    >
                      {copied === 'skills' ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                      {copied === 'skills' ? 'Copied!' : 'Copy'}
                    </button>
                  </div>
                </div>
                <pre className="bg-gray-900 border border-gray-700 rounded-lg p-4 text-sm text-gray-300 font-mono whitespace-pre-wrap overflow-auto max-h-[500px]">
                  {generatedSkillsMd}
                </pre>
              </div>
            )}
          </div>

          {/* Full Export */}
          <div className="card">
            <div className="flex items-center justify-between mb-3">
              <h3 className="text-sm font-semibold text-white">Full Export (Command + Skills.md)</h3>
              <div className="flex gap-2">
                <button
                  onClick={() => copyToClipboard(fullExport, 'full')}
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-violet-500/20 text-violet-300 hover:bg-violet-500/30 transition-all text-sm"
                >
                  {copied === 'full' ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                  {copied === 'full' ? 'Copied!' : 'Copy All'}
                </button>
              </div>
            </div>
            <pre className="bg-gray-900 border border-gray-700 rounded-lg p-4 text-xs text-gray-400 font-mono whitespace-pre-wrap overflow-auto max-h-[300px]">
              {fullExport}
            </pre>
          </div>

          {/* Quick Preview */}
          <div className="card">
            <button
              onClick={() => setShowPreview(!showPreview)}
              className="flex items-center justify-between w-full text-left"
            >
              <h3 className="text-sm font-semibold text-white">Quick Preview</h3>
              {showPreview ? <ChevronUp className="w-4 h-4 text-gray-400" /> : <ChevronDown className="w-4 h-4 text-gray-400" />}
            </button>
            {showPreview && (
              <div className="mt-3 space-y-2 text-sm">
                <div className="flex justify-between">
                  <span className="text-gray-400">Name:</span>
                  <span className="text-white">{name || '—'}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-400">Provider:</span>
                  <span className="text-white">{provider}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-400">Model:</span>
                  <span className="text-white">{model}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-400">Temperature:</span>
                  <span className="text-white">{temperature}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-400">Max Tokens:</span>
                  <span className="text-white">{maxTokens}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-400">Skills:</span>
                  <span className="text-white">{enabledSkills.length} enabled</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-400">System Prompt:</span>
                  <span className="text-white">{systemPrompt ? `${systemPrompt.length} chars` : '—'}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-400">Instructions:</span>
                  <span className="text-white">{instructions ? `${instructions.length} chars` : '—'}</span>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}
